agents:
  - name: root_agent
    type: root
    config:
      orchestrator_id: orchestrator
      
  - name: water_agent
    type: water_quality
    
  - name: fish_agent
    type: fish_health
    
  - name: plant_agent
    type: plant_growth
    
  - name: bacteria_agent
    type: bacteria
    
  - name: environment_agent
    type: environment